Config = {}

--API

-- https://open-meteo.com/

-- DEBUG 

Config.DEBUG = true -- DEBUG! // Server Side

-- SETTINGS // ONLY USE IF YOU KNOW WHAT YOUR DOING 

-- LOCATION
 
 
Config.TimeZone = "America/Los_Angeles"
Config.latitude = "52.52"
Config.longitude = "13.419998"

Config.SyncIntervall = 15 -- min 

-- WEATHER

Config.SyncWind = true -- Should the wind be synced // if false the wind is randomly generated by the game engine
Config.SyncWeather = true -- Should the weather like sunny and rainy be synced // if false the weather is randomly generated by the game engine 


